export default {
    
    ARROW_BLUE_COLOR: 0x4b8fff,
    ARROW_RED_COLOR: 0xff4b4b,
    ARROW_ROTATE_SPEED: 1.8,
    ARROW_STARTING_POSITION_X: 100,

    CAPTURING_SPEED: 0.007,

    CAPTURE_BLUE_COLOR: '#4b8fff',
    CAPTURE_RED_COLOR: '#ff4b4b',

    ARROW_MOVE_SPEED: 4,

    BACKGROUND_COLOR: '#CBCEC6',
}

